services:
  web:
    build: .
    ports: 
      - "5000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres:latest
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank_simulator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:

