services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "5000:80"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank_simulator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:

