"""Add admin_permission to users table

Revision ID: 817d30538567
Revises: 496af66ac616
Create Date: 2025-01-29 13:14:36.704132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817d30538567'
down_revision = '496af66ac616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_permission', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin_permission')

    # ### end Alembic commands ###
