"""Fixed relationships between UserModel and TransactionModel 2

Revision ID: 92d0bb7a5655
Revises: 0c004ff6cad9
Create Date: 2025-01-30 13:16:40.784050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d0bb7a5655'
down_revision = '0c004ff6cad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('transactions_sender_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('transactions_receiver_id_fkey', type_='foreignkey')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('transactions_receiver_id_fkey', 'users', ['receiver_id'], ['id'])
        batch_op.create_foreign_key('transactions_sender_id_fkey', 'users', ['sender_id'], ['id'])

    # ### end Alembic commands ###
